// @sketchyicons/angular: the icons as data, drawn by one component.
//
// The other frameworks get a component per icon because that costs them
// nothing. Angular compiles a template and a decorator for every component, so
// 1756 of them would be 1756 things for the compiler to chew through in every
// consumer's build. One component takes the icon as an input instead, which is
// what @lucide/angular does too.

import { banner, nodesLiteral, readAliases } from '../lib/icons.mjs';

export default {
  name: 'angular',
  package: 'packages/angular',

  /** @param {import('../lib/icons.mjs').Icon[]} icons */
  files(icons) {
    const aliases = readAliases(icons);

    const perIcon = icons.map((icon) => ({
      path: `src/icons/${icon.name}.ts`,
      content:
        `${banner(icon)}\n` +
        "import type { IconNode } from '../lib/types.js';\n\n" +
        `const ${icon.component}: IconNode = ${nodesLiteral(icon)};\n\n` +
        `export default ${icon.component};\n` +
        `export { ${icon.component} };\n`,
    }));

    // A name Lucide has renamed re-exports the icon it became, so migrating is
    // an import change and nothing else.
    const perAlias = aliases.map((alias) => ({
      path: `src/icons/${alias.name}.ts`,
      content:
        `// Generated by tools/build-targets.mjs. ${alias.component} is what Lucide used to\n` +
        `// call ${alias.targetComponent}, kept so an import from lucide resolves unchanged.\n\n` +
        `export { default, ${alias.targetComponent} as ${alias.component} } from './${alias.target}.js';\n`,
    }));

    const barrel =
      '// Generated by tools/build-targets.mjs. Do not edit.\n\n' +
      "export { SketchyIconComponent } from './lib/icon.component.js';\n" +
      "export type { IconNode, IconNodeAttributes } from './lib/types.js';\n\n" +
      icons
        .map((icon) => `export { default as ${icon.component} } from './icons/${icon.name}.js';`)
        .join('\n') +
      '\n' +
      (aliases.length
        ? '\n// Names Lucide has since renamed, kept so migrating is an import change.\n' +
          aliases
            .map(
              (alias) =>
                `export { ${alias.targetComponent} as ${alias.component} } from './icons/${alias.target}.js';`,
            )
            .join('\n') +
          '\n'
        : '');

    return [...perIcon, ...perAlias, { path: 'src/public-api.ts', content: barrel }];
  },
};
