// The shape every component package shares.
//
// One file per icon, not a barrel of 1756 exports, because a consumer importing
// one icon must not pull in the rest. The barrel exists on top for people who
// want it and is pure re-exports, so a bundler can drop what is unused.
//
// Everything a framework does differently lives in that package's create-icon,
// not here, so a new target is a name and a path.

import { banner, nodesLiteral, readAliases } from '../lib/icons.mjs';

/**
 * @param {{ name: string, package: string }} target
 */
export function componentTarget(target) {
  return {
    ...target,

    /** @param {import('../lib/icons.mjs').Icon[]} icons */
    files(icons) {
      const aliases = readAliases(icons);

      const perIcon = icons.map((icon) => ({
        path: `src/icons/${icon.name}.ts`,
        content:
          `${banner(icon)}\n` +
          "import createSketchyIcon from '../create-icon.js';\n\n" +
          `const ${icon.component} = /* @__PURE__ */ createSketchyIcon('${icon.component}', ${nodesLiteral(icon)});\n\n` +
          `export default ${icon.component};\n` +
          `export { ${icon.component} };\n`,
      }));

      // A name Lucide has renamed re-exports the icon it became, so migrating is
      // an import change and nothing else. These carry no geometry of their own.
      const perAlias = aliases.map((alias) => ({
        path: `src/icons/${alias.name}.ts`,
        content:
          `// Generated by tools/build-targets.mjs. ${alias.component} is what Lucide used to\n` +
          `// call ${alias.targetComponent}, kept so an import from lucide resolves unchanged.\n\n` +
          `export { default, ${alias.targetComponent} as ${alias.component} } from './${alias.target}.js';\n`,
      }));

      const barrel =
        '// Generated by tools/build-targets.mjs. Do not edit.\n\n' +
        "export { default as createSketchyIcon } from './create-icon.js';\n" +
        "export type { IconNode, IconNodeAttributes, SketchyIcon, SketchyIconProps } from './types.js';\n\n" +
        icons
          .map((icon) => `export { default as ${icon.component} } from './icons/${icon.name}.js';`)
          .join('\n') +
        '\n' +
        (aliases.length
          ? '\n// Names Lucide has since renamed, kept so migrating is an import change.\n' +
            aliases
              .map(
                (alias) =>
                  `export { ${alias.targetComponent} as ${alias.component} } from './icons/${alias.target}.js';`,
              )
              .join('\n') +
            '\n'
          : '');

      return [...perIcon, ...perAlias, { path: 'src/index.ts', content: barrel }];
    },
  };
}
