// @sketchyicons/data: the geometry, no framework, no dependency.
//
// One module of named constants rather than one module per icon. A bundler drops
// the constants nobody imported, so tree shaking still works, and a consumer
// building their own renderer wants all of them anyway.

import { banner, nodesLiteral, readAliases } from '../lib/icons.mjs';

export default {
  name: 'data',
  package: 'packages/data',

  /** @param {import('../lib/icons.mjs').Icon[]} icons */
  files(icons) {
    const aliases = readAliases(icons);
    const constants = icons
      .map(
        (icon) =>
          `${banner(icon)}export const ${icon.component}: IconNode = ${nodesLiteral(icon)};\n`,
      )
      .join('\n');

    const aliasConstants = aliases
      .map(
        (alias) =>
          `// ${alias.component} is what Lucide used to call ${alias.targetComponent}.\n` +
          `export const ${alias.component}: IconNode = ${alias.targetComponent};\n`,
      )
      .join('\n');

    const aliasEntries = aliases
      .map((alias) => `  ['${alias.name}', '${alias.target}'],`)
      .join('\n');

    const names = icons.map((icon) => `  '${icon.name}',`).join('\n');
    const components = icons.map((icon) => `  '${icon.component}',`).join('\n');

    return [
      {
        path: 'src/icons.ts',
        content:
          '// Generated by tools/build-targets.mjs. Do not edit.\n' +
          "import type { IconNode } from './types.js';\n\n" +
          constants +
          (aliasConstants ? `\n${aliasConstants}` : ''),
      },
      {
        path: 'src/names.ts',
        content:
          '// Generated by tools/build-targets.mjs. Do not edit.\n\n' +
          '/** Every icon name, in kebab case, in name order. */\n' +
          `export const iconNames = [\n${names}\n] as const;\n\n` +
          '/** Every icon name as the framework packages export it. */\n' +
          `export const componentNames = [\n${components}\n] as const;\n\n` +
          'export type IconName = (typeof iconNames)[number];\n' +
          'export type ComponentName = (typeof componentNames)[number];\n\n' +
          '/** Every name Lucide has renamed, and the icon it became. */\n' +
          `export const renamed: readonly (readonly [old: string, now: IconName])[] = [\n${aliasEntries}\n];\n`,
      },
      {
        path: 'src/index.ts',
        content:
          '// Generated by tools/build-targets.mjs. Do not edit.\n\n' +
          "export * from './icons.js';\n" +
          "export * from './names.js';\n" +
          "export type { IconNode, IconNodeAttributes } from './types.js';\n",
      },
    ];
  },
};
