// @sketchyicons/svelte: the icons as data, drawn by one component.
//
// A Svelte component is a file the consumer's bundler compiles, so a component
// per icon would be 1756 compilations in every build that uses one. One
// component takes the icon as a prop instead, the same shape the Angular target
// takes and for the same reason.

import { banner, nodesLiteral, readAliases } from '../lib/icons.mjs';

export default {
  name: 'svelte',
  package: 'packages/svelte',
  clean: ['src/lib/icons'],

  /** @param {import('../lib/icons.mjs').Icon[]} icons */
  files(icons) {
    const aliases = readAliases(icons);

    const perIcon = icons.map((icon) => ({
      path: `src/lib/icons/${icon.name}.ts`,
      content:
        `${banner(icon)}\n` +
        "import type { IconNode } from '../types.js';\n\n" +
        `const ${icon.component}: IconNode = ${nodesLiteral(icon)};\n\n` +
        `export default ${icon.component};\n` +
        `export { ${icon.component} };\n`,
    }));

    // A name Lucide has renamed re-exports the icon it became, so migrating is
    // an import change and nothing else.
    const perAlias = aliases.map((alias) => ({
      path: `src/lib/icons/${alias.name}.ts`,
      content:
        `// Generated by tools/build-targets.mjs. ${alias.component} is what Lucide used to\n` +
        `// call ${alias.targetComponent}, kept so an import from lucide resolves unchanged.\n\n` +
        `export { default, ${alias.targetComponent} as ${alias.component} } from './${alias.target}.js';\n`,
    }));

    const barrel =
      '// Generated by tools/build-targets.mjs. Do not edit.\n\n' +
      "export { default as SketchyIcon } from './Icon.svelte';\n" +
      "export type { IconNode, IconNodeAttributes, SketchyIconProps } from './types.js';\n\n" +
      icons
        .map((icon) => `export { default as ${icon.component} } from './icons/${icon.name}.js';`)
        .join('\n') +
      '\n' +
      (aliases.length
        ? '\n// Names Lucide has since renamed, kept so migrating is an import change.\n' +
          aliases
            .map(
              (alias) =>
                `export { ${alias.targetComponent} as ${alias.component} } from './icons/${alias.target}.js';`,
            )
            .join('\n') +
          '\n'
        : '');

    return [...perIcon, ...perAlias, { path: 'src/lib/index.ts', content: barrel }];
  },
};
